# Generated by Django 5.1.1 on 2024-09-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exchange_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
